uploads = []
generated = []

[[outputs]]
id = "HwrthQdhaV48nW7S75owj"
uri = "file://artifacts/kingdoms-conquest/dist/kingdoms-conquest.zip"
type = "unspecified"
title = "Kingdoms & Conquest (.mcaddon)"
